version: '3'

services:
  vue-frontend:
    container_name: vue-frontend
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"


